name    'treydock-zram'
version '0.0.1'
source 'git://github.com/treydock/puppet-zram.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'zram Puppet module'
description 'zram Puppet module'
project_page 'http://github.com/treydock/puppet-zram'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
