#!/bin/sh

RETVAL=0

num_cpus=$(grep -c processor /proc/cpuinfo)
[ "$num_cpus" != 0 ] || num_cpus=1

[ -f /etc/default/zram ] && source /etc/default/zram || true
[ -z $FACTOR ] && factor=80 || factor=$FACTOR # percentage
[ -z $DEVICE_DISKSIZE ] && device_disksize=0 || device_disksize=$DEVICE_DISKSIZE
[ -z $NUM_DEVICES ] && num_devices=$num_cpus || num_devices=$NUM_DEVICES
[ -z $SWAP ] && swap=1 || swap=$SWAP
[ -z $ZFS ] && zfs=0 || zfs=$ZFS
[ -z $ZPOOL_NAME ] && zpool_name='tank' || zpool_name=$ZPOOL_NAME

if [ "$device_disksize" != 0 ]; then
  mem_per_device=$device_disksize
else
  memtotal=$(grep MemTotal /proc/meminfo | awk ' { print $2 } ')
  mem_per_device=$(($memtotal/$num_devices*$factor/100*1024))
fi

modprobe -q zram num_devices=$num_devices
RETVAL=$?
[ $RETVAL -ne 0 ] && exit $RETVAL

for zram in /dev/zram*; do
  z=$(basename $zram)
  echo $mem_per_device > /sys/block/$z/disksize
  RETVAL=$?

  if [ "$SWAP" == 1 ]; then
    mkswap $zram
    RETVAL=$?
    swapon -p 100 $zram
    RETVAL=$?
  fi

  if [ "$ZFS" == 1 ]; then
    zpool add $zpool_name cache $z
    RETVAL=$?
  fi
done

exit $RETVAL
