#!/bin/sh

RETVAL=0

[ -f /etc/default/zram ] && source /etc/default/zram || true
[ -z $SWAP ] && swap=1 || swap=$SWAP
[ -z $ZFS ] && zfs=0 || zfs=$ZFS
[ -z $ZPOOL_NAME ] && zpool_name='tank' || zpool_name=$ZPOOL_NAME

for zram in /dev/zram*; do
  z=$(basename $zram)

  grep -q "$zram" /proc/swaps && swapoff $zram
  RETVAL=$?
  
  if [ "$ZFS" == 1 ]; then
    zpool remove $zpool_name $z
    RETVAL=$?
  fi
done

sleep 1
rmmod zram

exit $RETVAL
